# Artificial Neural Network

### Importing the libraries

In [30]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [31]:
tf.__version__

'2.4.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [32]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values #เอาตั้งแต่ column ที่  3 และไม่เอา column สุดท้าย (เริ่มนับจาก 0)
y = dataset.iloc[:, -1].values

In [33]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [34]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [35]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2]) #แปลงค่า column ที่ 2 จาก str เป็น number Female =0 ,male = 1 (เรียงลำดับตามตัวอักษร )

In [36]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [37]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

[1] #columns ที่เราต้องการเปลี่ยน 

In [38]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [39]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

สำคัญในการทำ Deep learning 

In [40]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [41]:
ann = tf.keras.models.Sequential() #เรียกใช้  library from Tensorflw for doing ANN

### Adding the input layer and the first hidden layer

In [42]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) #unit = new feature = hidden neuron ไม่มีกฏในการกำหนด เลือกและลองไปเรื่อยๆ , Activation คือสมการประมาณการที่เราเลือกใช้ ซึ่งที่นิยมคือ rectifier activation (relu)

### Adding the second hidden layer

In [43]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [44]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid')) 

ในขั้นตอนสุดท้าย คือ output เราจะกำหนดให้ผลที่ออกมามีกี่ค่า ขึ้นนนอยู่ว่า เรามีการแบ่ง class เท่าไร ถ้า binary จะมี 1 dimension ถ้า 3 class จะมี 3 dimension  ในที่นี้เราแบ่งแบบ binary ดังนั้นเรากำหนด unit = 1

---
และเรากำหนด activation function คือ sigmoid เนื่องจากเราต้องการ ให้ค่าสุดท้ายออกมาเป็นค่า probability 


---

แต่ในกรณีที่ เราไม่ได้ต้องการแบ่ง class แบบ binary เราก็ไม่ควรใช้ sigmoid เราควรใช้ softmax


## Part 3 - Training the ANN

### Compiling the ANN

In [45]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

complie เป็นการเลือกใช้คำสั่งว่าเราต้องการให้ model ที่เราสร้าง นั้นแสดงผลอะไรบ้าง เราต้องการให้มัน optimize แสดงค่า codt function และ แสดง accuracy  

---

loss = binary_crossentropy เราใช้อันนี้เนืองจากเราแบ่งข้อมูลเป็น binary แต่ถ้าไม่ เราควรที่จะเลือก loss function แบบอื่น

### Training the ANN on the Training set

In [46]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100) # 32 เป็น defult , epochs = 

Epoch 1/100
250/250 [==============================] - 1s 832us/step - loss: 0.5151 - accuracy: 0.7945
Epoch 2/100
250/250 [==============================] - 0s 743us/step - loss: 0.4581 - accuracy: 0.7920
Epoch 3/100
250/250 [==============================] - 0s 950us/step - loss: 0.4398 - accuracy: 0.7964
Epoch 4/100
250/250 [==============================] - 0s 894us/step - loss: 0.4339 - accuracy: 0.7918
Epoch 5/100
250/250 [==============================] - 0s 953us/step - loss: 0.4306 - accuracy: 0.7932
Epoch 6/100
250/250 [==============================] - 0s 940us/step - loss: 0.4162 - accuracy: 0.8185
Epoch 7/100
250/250 [==============================] - 0s 898us/step - loss: 0.4122 - accuracy: 0.8205
Epoch 8/100
250/250 [==============================] - 0s 900us/step - loss: 0.4105 - accuracy: 0.8265
Epoch 9/100
250/250 [==============================] - 0s 928us/step - loss: 0.4033 - accuracy: 0.8313
Epoch 10/100
250/250 [==============================] - 0s 893us/step - l

Epoch ทำงานร่วมกับ batch size ซึ่งมันจะทำงาน 32 step in 1 Epoch และ Epoch จำนวนมาก ไม่ได้หมายความว่า accuracy จะสูงตามไปด้วย ซึ่งเราต้องสุ่มเอา 

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Solution**

In [ ]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [48]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [50]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1524   71]
 [ 210  195]]


0.8595